### ISSUE TITLE
Sample react 16.8

### ISSUE THREAD

**Issue by haf** [locize/locize-examples#2]
Hi,

Do you have a sample with i18next and latest react that doesn't use globals/window.locize? I would like to bundle everything with webpack.

Regards,

**Comment by adrai** [comment]
Something like this? https://github.com/i18next/react-i18next/tree/master/example/react/src + locize settings: https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/locize/src/i18n.js

**Comment by haf** [comment]
@adrai Yes exactly that; I was avoiding older samples, but there it is.

Are there any details on how to set up a CI/CD pipeline with locize?

**Comment by adrai** [comment]
You have the possibility to use the cli (https://github.com/locize/locize-cli) or directly the api (https://docs.locize.com/integration/api).

And there are also webhooks (https://docs.locize.com/integration/webhook), slack (https://docs.locize.com/more/notifications), the saveMissing feature of i18next (https://www.i18next.com/overview/configuration-options#missing-keys), last used plugin (https://github.com/locize/locize-lastused), in-context-editor (https://docs.locize.com/more/incontext-editor), etc... 😉

**Comment by haf** [comment]
Ref https://github.com/locize/i18next-node-locize-backend/issues/3#issuecomment-462148036

**Comment by haf** [comment]
Ok, last question (promise!) the above but with `next-i18next`—next.js support as well? next-i18next doesn't really expose its i18n configuration in its sample.

**Comment by jamuhl** [comment]
https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L30 there seems to be a `use` array you can pass for configuration

**Comment by haf** [comment]
@jamuhl I tried; the problem is that I have to conditionally only give it if it's running on the server.

EDIT:

```js
// https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/locize
const defaultConfig = {
  defaultLanguage: 'en',
  otherLanguages: ['sv'],
  use: process.browser ? [] : [ require('i18next-node-locize-backend') ]
}
```

works, but it's badly configured and crashes when trying to read an absolute path:

```
Error: Invalid URI "/Users/h/dev/qv2/static/locales/en/common.json"
```

**Comment by jamuhl** [comment]
looks more like the default setting for the i18next-fs-backend triggers here -> did you pass in the backend settings for the i18next-node-locize-backend?

**Comment by haf** [comment]
I've tried both as a property `backend` on the config object, and

<img width="553" alt="image" src="https://user-images.githubusercontent.com/193115/57104375-76289000-6d28-11e9-884f-238fd7d69ccd.png">

both throw the above error.

**Comment by jamuhl** [comment]
I would ask how to do it properly at the next-i18next repo - @isaachinman for sure will help you out with this.

Alternative just sync your translations to the express server using our CLI: https://github.com/locize/locize-cli#download-current-published-files

**Comment by haf** [comment]
This all now works with these keys in config:

- defaultLanguage
- otherLanguages
- use
- debug
- saveMissing
- defaultNS
- backend

and these in backend:

- loadPath
- addPath
- referenceLng
- projectId
- apiKey
- version
- allowedAddOrUpdateHosts

Thanks for helping me getting it working. If you want to track this issue as "add a react sample", feel free to reopen.

**Comment by datainvestor** [comment]
Did you manage to use in context editor with NextJS?

**Comment by adrai** [comment]
> Did you manage to use in context editor with NextJS?

just use it like this: https://github.com/locize/next-i18next-locize/blob/main/next-i18next.config.js#L27
